### ISSUE TITLE
Numbered menu doesn't work on Adrenaline

### ISSUE THREAD

**Issue by ghost** [DniweTamp/Persona-3-Portable-Mod-Menu#1]
Hi, basically what the title says; I'm trying to use the Mod Menu on an american copy of P3P with other mods, and it works, until I need to access a numbered menu (like Sound Test); when I try to access them, the game crashes and I don't know what to do
Curiously enough, it works on PPSSPP...
If you have any tip on running it on Adrenaline or if its actually a bug, please tell me ASAP
thanks in advance!

**Comment by DniweTamp** [comment]
fixed on latest release
